// GENERATED by scripts/gen-templates.mjs — do not hand-edit.
// Re-run: node scripts/gen-templates.mjs   (verify: node scripts/gen-templates.mjs --check)
// Metadata only: safe to serve to anyone. Geometry for paid templates lives in
// lib/template-geometry.ts (server-only) and is never bundled or served unpaid.

export type TemplateCategory = "indian" | "office" | "other";

export interface TemplateCatalogEntry {
  key: string;
  name: string;
  cat: TemplateCategory;
  desc: string;
  /** paid templates: geometry withheld until a template_unlock purchase exists */
  paid: boolean;
}

export const TEMPLATE_CATALOG: TemplateCatalogEntry[] = [
  {
    "key": "in_1bhk",
    "name": "1BHK Compact Indian House",
    "cat": "indian",
    "desc": "Veranda, living room, kitchen, bedroom and bath",
    "paid": false
  },
  {
    "key": "in_2bhk",
    "name": "2BHK Indian Family Home",
    "cat": "indian",
    "desc": "Family hall, kitchen, two bedrooms and two baths",
    "paid": false
  },
  {
    "key": "in_3bhk",
    "name": "3BHK Modern Indian Home",
    "cat": "indian",
    "desc": "Living hall, kitchen, three bedrooms, bath and balcony",
    "paid": false
  },
  {
    "key": "in_vastu",
    "name": "Vastu 2BHK Home",
    "cat": "indian",
    "desc": "Living, kitchen and bedrooms arranged in vastu zones",
    "paid": false
  },
  {
    "key": "in_villa",
    "name": "South Indian Courtyard Villa",
    "cat": "indian",
    "desc": "Front and rear verandas with three bedrooms",
    "paid": false
  },
  {
    "key": "in_kothi",
    "name": "North Indian Kothi (4BHK)",
    "cat": "indian",
    "desc": "Foyer, living, kitchen, four bedrooms and balconies",
    "paid": false
  },
  {
    "key": "in_row",
    "name": "Builder Floor / Row House",
    "cat": "indian",
    "desc": "Long home with porch, living, kitchen and two bedrooms",
    "paid": false
  },
  {
    "key": "in_village",
    "name": "1KTH Village House",
    "cat": "indian",
    "desc": "Front veranda, large hall, kitchen and bathroom",
    "paid": false
  },
  {
    "key": "in_courtyard",
    "name": "Traditional Courtyard House",
    "cat": "indian",
    "desc": "Perimeter rooms around a central family hall",
    "paid": false
  },
  {
    "key": "in_bungalow",
    "name": "Luxury 5BHK Indian Villa",
    "cat": "indian",
    "desc": "Grand hall, kitchen, five bedrooms, baths and balconies",
    "paid": false
  },
  {
    "key": "off_startup",
    "name": "Startup Open-Plan Office",
    "cat": "office",
    "desc": "Reception, open desk bays, meeting room, pantry and washroom",
    "paid": true
  },
  {
    "key": "off_exec",
    "name": "Corporate Executive Suite",
    "cat": "office",
    "desc": "Reception, boardroom, executive cabins, pantry and washroom",
    "paid": true
  },
  {
    "key": "off_tech",
    "name": "Tech Agency Agile Hub",
    "cat": "office",
    "desc": "Two agile work bays, huddle room, coffee bar and washroom",
    "paid": true
  },
  {
    "key": "off_cowork",
    "name": "Co-Working Space",
    "cat": "office",
    "desc": "Reception, hot desks, private booths, café and meeting room",
    "paid": true
  },
  {
    "key": "off_studio",
    "name": "Design & Creative Studio",
    "cat": "office",
    "desc": "Gallery entry, drafting bay, client pitch room and library",
    "paid": true
  },
  {
    "key": "off_clinic",
    "name": "Medical / Clinic Suite",
    "cat": "office",
    "desc": "Waiting room, reception, three consultation rooms and washroom",
    "paid": true
  },
  {
    "key": "off_law",
    "name": "Law Firm & Partners Office",
    "cat": "office",
    "desc": "Reception, conference room, library and four partner cabins",
    "paid": true
  },
  {
    "key": "off_finance",
    "name": "Financial & Accounting Firm",
    "cat": "office",
    "desc": "Client lounge, accountant work bay, archive and washroom",
    "paid": true
  },
  {
    "key": "off_retail",
    "name": "Retail Showroom & Back Office",
    "cat": "office",
    "desc": "Showroom, counter, back office, inventory room and washroom",
    "paid": true
  },
  {
    "key": "off_bpo",
    "name": "Call Center / BPO Floor",
    "cat": "office",
    "desc": "Large agent bays, manager cabin, cafeteria and washroom",
    "paid": true
  },
  {
    "key": "off_realestate",
    "name": "Real Estate Sales Suite",
    "cat": "office",
    "desc": "Model foyer, presentation lounge, closing rooms and pantry",
    "paid": true
  },
  {
    "key": "off_satellite",
    "name": "Satellite Hub Workspace",
    "cat": "office",
    "desc": "Coffee lounge, four private offices and shared meeting room",
    "paid": true
  },
  {
    "key": "oth_japandi",
    "name": "Japandi Minimalist Villa",
    "cat": "other",
    "desc": "Open veranda, minimalist living, kitchen and master suite",
    "paid": true
  },
  {
    "key": "oth_cabin",
    "name": "Nordic Timber Cabin",
    "cat": "other",
    "desc": "Deck, great room, kitchenette and compact bath",
    "paid": true
  },
  {
    "key": "oth_loft",
    "name": "Contemporary Open Loft",
    "cat": "other",
    "desc": "Double-height style living, kitchen, bedroom and luxury bath",
    "paid": true
  },
  {
    "key": "oth_wellness",
    "name": "Yoga & Wellness Studio",
    "cat": "other",
    "desc": "Reception lounge, practice hall, changing room and bath",
    "paid": true
  },
  {
    "key": "oth_training",
    "name": "Education & Training Hub",
    "cat": "other",
    "desc": "Lecture hall, seminar rooms, administration office and bath",
    "paid": true
  },
  {
    "key": "oth_cafe",
    "name": "Boutique Cafe & Kitchen",
    "cat": "other",
    "desc": "Dining lounge, coffee bar, kitchen and guest washroom",
    "paid": true
  },
  {
    "key": "oth_tiny",
    "name": "Micro Tiny House",
    "cat": "other",
    "desc": "Living/kitchen room, wet bath and front deck",
    "paid": true
  },
  {
    "key": "oth_townhouse",
    "name": "Multi-Level Townhouse",
    "cat": "other",
    "desc": "Living, kitchen, stairs, bedroom and bath starter layout",
    "paid": true
  },
  {
    "key": "empty",
    "name": "Empty — single hall",
    "cat": "other",
    "desc": "Start from a single blank room",
    "paid": false
  }
];

export const TEMPLATE_KEYS = new Set(TEMPLATE_CATALOG.map((t) => t.key));

export function isPaidTemplate(key: string): boolean {
  return TEMPLATE_CATALOG.some((t) => t.key === key && t.paid);
}
