import "server-only";

// GENERATED by scripts/gen-templates.mjs — do not hand-edit.
// Re-run: node scripts/gen-templates.mjs   (verify: node scripts/gen-templates.mjs --check)
// Geometry for the 20 PAID templates. This module must never be imported from a
// client component: it is the thing customers pay for. Free templates keep their
// geometry inline in builder.html.
//
// Payload shape: plans/02-template-v2-contract.md. Every template below is v2.
// The v1 tuple form is still part of the exported type so a not-yet-migrated
// template could be served unchanged, and so the reader contract stays honest.

/** v1 room: [roomType, centerX, centerZ, opts] where opts has only doors/wins. */
export type LegacyRoomSpec = [string, number, number, Record<string, unknown>?];

/** `[wall, t, type?, width?, height?]` — wall 0=+z 1=+x 2=-z 3=-x, t in 0..1 */
export type DoorTuple = [number, number, string?, number?, number?];
/** `[wall, t, kind?]` — kind "std" (default) | "pano" (floor-to-ceiling) */
export type WindowTuple = [number, number, ("std" | "pano")?];
/** `[key, lx, lz, rot?]` — room-local metres; lx along len, lz along w */
export type FurnitureTuple = [string, number, number, number?];

/** v2 room. Presence of `furniture` REPLACES auto-furnish for that room. */
export interface RoomSpecV2 {
  /** key in C.rooms */
  type: string;
  /** metres, world X of the room centre */
  cx: number;
  /** metres, world Z of the room centre */
  cz: number;
  /** quarter turns, int 0-3 (default 0) */
  rot?: number;
  /** metres (default C.rooms[type].w) — extent across the room */
  w?: number;
  /** metres (default C.rooms[type].len) — extent along the room */
  len?: number;
  name?: string;
  /** key in C.paint */
  paint?: string;
  /** key in C.floorCol */
  floorCol?: string;
  doors?: DoorTuple[];
  wins?: WindowTuple[];
  furniture?: FurnitureTuple[];
}

export type RoomSpec = LegacyRoomSpec | RoomSpecV2;

export type TemplateProfile = "home" | "office";

/** legacy payload: no `v` (or v:1) and v1 tuple rooms */
export interface TemplateGeometryV1 {
  v?: 1;
  profile: TemplateProfile;
  rooms: LegacyRoomSpec[];
}

/** v2 payload — see plans/02-template-v2-contract.md §1 */
export interface TemplateGeometryV2 {
  v: 2;
  profile: TemplateProfile;
  rooms: RoomSpecV2[];
}

export type TemplateGeometry = TemplateGeometryV1 | TemplateGeometryV2;

const PAID_TEMPLATE_GEOMETRY: Record<string, TemplateGeometry> = {
  "off_startup": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hall",
        "cx": 2.8,
        "cz": 2.4,
        "w": 4.8,
        "len": 5.6,
        "name": "Reception",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [2,0.232,"ext_glass",1.8,2.3],
          [0,0.839,"int_hard",0.85,2.05]
        ],
        "wins": [
          [2,0.732,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["desk",-1.4,-1],
          ["chair",-1.4,-0.1,2],
          ["sofa",1.4,-1.2],
          ["coffee",1.4,-0.2],
          ["plant",2.3,1.6],
          ["plant",-2.3,1.6]
        ]
      },
      {
        "type": "hall",
        "cx": 7.5,
        "cz": 2.4,
        "w": 4.8,
        "len": 3.8,
        "name": "Meeting room",
        "paint": "greige",
        "floorCol": "ash",
        "doors": [
          [0,0.5,"int_hard",0.85,2.05]
        ],
        "wins": [
          [2,0.5,"pano"]
        ],
        "furniture": [
          ["table",-0.95,-0.2],
          ["chair",-0.95,-1.15],
          ["chair",-0.95,0.75,2],
          ["table",0,-0.2],
          ["chair",0,-1.15],
          ["chair",0,0.75,2],
          ["table",0.95,-0.2],
          ["chair",0.95,-1.15],
          ["chair",0.95,0.75,2],
          ["plant",1.4,1.4]
        ]
      },
      {
        "type": "hallway",
        "cx": 3.25,
        "cz": 5.5,
        "w": 1.4,
        "len": 6.5,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [1,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "hallway",
        "cx": 9.75,
        "cz": 5.5,
        "w": 1.4,
        "len": 6.5,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [3,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "kitchen",
        "cx": 11.2,
        "cz": 3.8,
        "w": 2,
        "len": 3.6,
        "name": "Pantry",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [0,0.5,"int_hard",0.85,2.05]
        ],
        "wins": [
          [2,0.5]
        ]
      },
      {
        "type": "bath",
        "cx": 12,
        "cz": 7.4,
        "w": 2.4,
        "len": 2,
        "name": "Washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.5,"int_pvc",0.8,2.05]
        ]
      },
      {
        "type": "hall",
        "cx": 3.5,
        "cz": 8.8,
        "w": 5.2,
        "len": 7,
        "name": "Open desk bay",
        "paint": "white",
        "floorCol": "oak",
        "doors": [
          [2,0.5,"int_hard",0.9,2.05]
        ],
        "wins": [
          [0,0.5,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["desk",-2.1,-1.15],
          ["chair",-2.1,-0.37,2],
          ["desk",0,-1.15],
          ["chair",0,-0.37,2],
          ["desk",2.1,-1.15],
          ["chair",2.1,-0.37,2],
          ["desk",-2.1,1.15],
          ["chair",-2.1,1.93,2],
          ["desk",0,1.15],
          ["chair",0,1.93,2],
          ["desk",2.1,1.15],
          ["chair",2.1,1.93,2],
          ["plant",2.9,-2]
        ]
      },
      {
        "type": "hall",
        "cx": 9,
        "cz": 8.8,
        "w": 5.2,
        "len": 4,
        "name": "Open desk bay",
        "paint": "white",
        "floorCol": "oak",
        "doors": [
          [2,0.5,"int_hard",0.9,2.05]
        ],
        "wins": [
          [0,0.5,"pano"]
        ],
        "furniture": [
          ["desk",-0.95,-1.15],
          ["chair",-0.95,-0.37,2],
          ["desk",0.95,-1.15],
          ["chair",0.95,-0.37,2],
          ["desk",-0.95,1.15],
          ["chair",-0.95,1.93,2],
          ["desk",0.95,1.15],
          ["chair",0.95,1.93,2],
          ["plant",-1.5,-2]
        ]
      },
      {
        "type": "bedroom",
        "cx": 12,
        "cz": 10,
        "w": 2.8,
        "len": 2,
        "name": "Server / store",
        "paint": "gray",
        "floorCol": "slate",
        "doors": [
          [3,0.5,"int_hard",0.85,2.05]
        ]
      }
    ]
  },
  "off_exec": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hall",
        "cx": 3,
        "cz": 2.5,
        "w": 5,
        "len": 6,
        "name": "Reception",
        "paint": "greige",
        "floorCol": "gtile",
        "doors": [
          [2,0.267,"ext_glass",2,2.4],
          [0,0.867,"int_hard",0.85,2.05]
        ],
        "wins": [
          [2,0.767,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["desk",-1.8,-1.2],
          ["chair",-1.8,-0.3,2],
          ["sofa",1.6,-1.4],
          ["coffee",1.6,-0.3],
          ["plant",2.5,1.8]
        ]
      },
      {
        "type": "hall",
        "cx": 9,
        "cz": 2.5,
        "w": 5,
        "len": 6,
        "name": "Boardroom",
        "paint": "beige",
        "floorCol": "walnut",
        "doors": [
          [0,0.5,"int_panel",0.9,2.1]
        ],
        "wins": [
          [2,0.5,"pano"]
        ],
        "furniture": [
          ["table",-2.1,0],
          ["chair",-2.1,-0.95],
          ["chair",-2.1,0.95,2],
          ["table",-1.05,0],
          ["chair",-1.05,-0.95],
          ["chair",-1.05,0.95,2],
          ["table",0,0],
          ["chair",0,-0.95],
          ["chair",0,0.95,2],
          ["table",1.05,0],
          ["chair",1.05,-0.95],
          ["chair",1.05,0.95,2],
          ["table",2.1,0],
          ["chair",2.1,-0.95],
          ["chair",2.1,0.95,2],
          ["plant",-2.3,1.4],
          ["tv",2.1,1.5]
        ]
      },
      {
        "type": "hall",
        "cx": 13.5,
        "cz": 2.5,
        "w": 5,
        "len": 3,
        "name": "Visitor lounge",
        "paint": "cream",
        "floorCol": "oak",
        "doors": [
          [0,0.5,"int_hard",0.85,2.05]
        ],
        "wins": [
          [1,0.5,"pano"]
        ],
        "furniture": [
          ["sofa",0,-1],
          ["coffee",0,0.1],
          ["chair",-1,0.9,1],
          ["chair",1,0.9,3],
          ["plant",1.1,-1.8]
        ]
      },
      {
        "type": "hallway",
        "cx": 3.75,
        "cz": 5.7,
        "w": 1.4,
        "len": 7.5,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [1,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "hallway",
        "cx": 11.25,
        "cz": 5.7,
        "w": 1.4,
        "len": 7.5,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [3,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "bedroom",
        "cx": 1.9,
        "cz": 8.5,
        "w": 4.2,
        "len": 3.8,
        "name": "Executive cabin",
        "paint": "beige",
        "floorCol": "walnut",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5,"pano"],
          [3,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 5.6,
        "cz": 8.5,
        "w": 4.2,
        "len": 3.6,
        "name": "Executive cabin",
        "paint": "beige",
        "floorCol": "walnut",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5,"pano"]
        ]
      },
      {
        "type": "bedroom",
        "cx": 9.2,
        "cz": 8.5,
        "w": 4.2,
        "len": 3.6,
        "name": "Executive cabin",
        "paint": "beige",
        "floorCol": "walnut",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5,"pano"]
        ]
      },
      {
        "type": "hallway",
        "cx": 11.7,
        "cz": 8.5,
        "rot": 1,
        "w": 1.4,
        "len": 4.2,
        "name": "Service corridor",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [1,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "kitchen",
        "cx": 13.7,
        "cz": 7.5,
        "w": 2.2,
        "len": 2.6,
        "name": "Pantry",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [3,0.5,"int_hard",0.85,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      },
      {
        "type": "bath",
        "cx": 13.7,
        "cz": 9.6,
        "w": 2,
        "len": 2.6,
        "name": "Washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [3,0.5,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [0,0.5]
        ]
      }
    ]
  },
  "off_tech": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hallway",
        "cx": 6.7,
        "cz": 3.5,
        "rot": 1,
        "w": 1.4,
        "len": 7,
        "name": "Entry spine",
        "paint": "white",
        "floorCol": "slate",
        "doors": [
          [1,0.5,"ext_glass",1.1,2.3]
        ]
      },
      {
        "type": "hall",
        "cx": 3,
        "cz": 3.5,
        "w": 7,
        "len": 6,
        "name": "Agile bay A",
        "paint": "gray",
        "floorCol": "oak",
        "doors": [
          [1,0.5,"int_hard",0.9,2.05]
        ],
        "wins": [
          [3,0.5,"pano"],
          [2,0.6,"pano"]
        ],
        "furniture": [
          ["desk",-1.15,-2.1],
          ["chair",-1.15,-1.32,2],
          ["desk",1.15,-2.1],
          ["chair",1.15,-1.32,2],
          ["desk",-1.15,0],
          ["chair",-1.15,0.78,2],
          ["desk",1.15,0],
          ["chair",1.15,0.78,2],
          ["desk",-1.15,2.1],
          ["chair",-1.15,2.88,2],
          ["desk",1.15,2.1],
          ["chair",1.15,2.88,2],
          ["plant",-2.4,2.4]
        ]
      },
      {
        "type": "hall",
        "cx": 10.4,
        "cz": 3.5,
        "w": 7,
        "len": 6,
        "name": "Agile bay B",
        "paint": "gray",
        "floorCol": "oak",
        "doors": [
          [3,0.5,"int_hard",0.9,2.05]
        ],
        "wins": [
          [1,0.5,"pano"],
          [2,0.4,"pano"]
        ],
        "furniture": [
          ["desk",-1.15,-2.1],
          ["chair",-1.15,-1.32,2],
          ["desk",1.15,-2.1],
          ["chair",1.15,-1.32,2],
          ["desk",-1.15,0],
          ["chair",-1.15,0.78,2],
          ["desk",1.15,0],
          ["chair",1.15,0.78,2],
          ["desk",-1.15,2.1],
          ["chair",-1.15,2.88,2],
          ["desk",1.15,2.1],
          ["chair",1.15,2.88,2],
          ["plant",2.4,2.4]
        ]
      },
      {
        "type": "hall",
        "cx": 2,
        "cz": 8.7,
        "w": 3.4,
        "len": 4,
        "name": "Huddle room",
        "paint": "sage",
        "floorCol": "ash",
        "doors": [
          [2,0.5,"int_hard",0.85,2.05]
        ],
        "wins": [
          [0,0.5,"pano"]
        ],
        "furniture": [
          ["table",-0.9,0],
          ["chair",-0.9,-0.95],
          ["chair",-0.9,0.95,2],
          ["table",0,0],
          ["chair",0,-0.95],
          ["chair",0,0.95,2],
          ["table",0.9,0],
          ["chair",0.9,-0.95],
          ["chair",0.9,0.95,2]
        ]
      },
      {
        "type": "kitchen",
        "cx": 5.8,
        "cz": 8.7,
        "w": 3.4,
        "len": 3.6,
        "name": "Coffee bar",
        "paint": "terra",
        "floorCol": "terra",
        "doors": [
          [2,0.722,"int_hard",0.85,2.05]
        ],
        "wins": [
          [0,0.5]
        ],
        "furniture": [
          ["kunit",0,-1.2],
          ["kunit",-1.3,0,1],
          ["fridge",1.3,-1],
          ["table",-0.5,0.8],
          ["chair",-0.5,0.1],
          ["chair",-0.5,1.3,2]
        ]
      },
      {
        "type": "bath",
        "cx": 8.7,
        "cz": 8.2,
        "w": 2.4,
        "len": 2.2,
        "name": "Washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.5,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      }
    ]
  },
  "off_cowork": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hall",
        "cx": 2.5,
        "cz": 2.2,
        "w": 4.4,
        "len": 5,
        "name": "Reception",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [2,0.26,"ext_glass",1.9,2.3],
          [0,0.84,"int_hard",0.85,2.05]
        ],
        "wins": [
          [2,0.74,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["desk",-1.1,-0.9],
          ["chair",-1.1,0,2],
          ["sofa",1.2,-1.1],
          ["plant",1.9,1.4]
        ]
      },
      {
        "type": "kitchen",
        "cx": 7,
        "cz": 2.2,
        "w": 4.4,
        "len": 4,
        "name": "Café",
        "paint": "terra",
        "floorCol": "terra",
        "doors": [
          [0,0.3,"int_hard",0.85,2.05]
        ],
        "wins": [
          [2,0.5,"pano"]
        ],
        "furniture": [
          ["kunit",-0.9,-1.5],
          ["fridge",1.4,-1.5],
          ["table",-0.6,0.7],
          ["chair",-1.55,0.7,1],
          ["chair",0.35,0.7,3],
          ["table",0.6,0.7],
          ["chair",-0.35,0.7,1],
          ["chair",1.55,0.7,3]
        ]
      },
      {
        "type": "hall",
        "cx": 11.8,
        "cz": 2.2,
        "w": 4.4,
        "len": 5.6,
        "name": "Meeting room",
        "paint": "greige",
        "floorCol": "ash",
        "doors": [
          [0,0.446,"int_hard",0.85,2.05]
        ],
        "wins": [
          [1,0.5,"pano"],
          [2,0.357,"pano"]
        ],
        "furniture": [
          ["table",-1.575,0],
          ["chair",-1.575,-0.95],
          ["chair",-1.575,0.95,2],
          ["table",-0.525,0],
          ["chair",-0.525,-0.95],
          ["chair",-0.525,0.95,2],
          ["table",0.525,0],
          ["chair",0.525,-0.95],
          ["chair",0.525,0.95,2],
          ["table",1.575,0],
          ["chair",1.575,-0.95],
          ["chair",1.575,0.95,2],
          ["tv",-1.9,1.8]
        ]
      },
      {
        "type": "hallway",
        "cx": 3.5,
        "cz": 5.1,
        "w": 1.4,
        "len": 7,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [1,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "hallway",
        "cx": 10.8,
        "cz": 5.1,
        "w": 1.4,
        "len": 7.6,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [3,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "hall",
        "cx": 3.8,
        "cz": 8.7,
        "w": 5.8,
        "len": 7.6,
        "name": "Hot desks",
        "paint": "white",
        "floorCol": "oak",
        "doors": [
          [2,0.539,"int_hard",0.9,2.05]
        ],
        "wins": [
          [0,0.5,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["desk",-2.2,-1.3],
          ["chair",-2.2,-0.52,2],
          ["desk",0,-1.3],
          ["chair",0,-0.52,2],
          ["desk",2.2,-1.3],
          ["chair",2.2,-0.52,2],
          ["desk",-2.2,1.3],
          ["chair",-2.2,2.08,2],
          ["desk",0,1.3],
          ["chair",0,2.08,2],
          ["desk",2.2,1.3],
          ["chair",2.2,2.08,2],
          ["plant",3.2,-2.3]
        ]
      },
      {
        "type": "bedroom",
        "cx": 8.8,
        "cz": 7.2,
        "w": 2.8,
        "len": 2.4,
        "name": "Private booth",
        "paint": "lavender",
        "floorCol": "ash",
        "doors": [
          [2,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "bedroom",
        "cx": 11.2,
        "cz": 7.2,
        "w": 2.8,
        "len": 2.4,
        "name": "Private booth",
        "paint": "lavender",
        "floorCol": "ash",
        "doors": [
          [2,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "bedroom",
        "cx": 13.5,
        "cz": 7.2,
        "w": 2.8,
        "len": 2.2,
        "name": "Private booth",
        "paint": "lavender",
        "floorCol": "ash",
        "doors": [
          [2,0.5,"int_hard",0.85,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      },
      {
        "type": "bath",
        "cx": 8.6,
        "cz": 9.8,
        "w": 2.4,
        "len": 2,
        "name": "Washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [3,0.5,"int_pvc",0.8,2.05]
        ]
      }
    ]
  },
  "off_studio": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hall",
        "cx": 4,
        "cz": 1.6,
        "w": 3.2,
        "len": 8,
        "name": "Gallery entry",
        "paint": "white",
        "floorCol": "slate",
        "doors": [
          [2,0.5,"ext_glass",2.2,2.4],
          [0,0.25,"int_hard",1,2.05]
        ],
        "wins": [
          [2,0.825,"pano"],
          [2,0.175,"pano"]
        ],
        "furniture": [
          ["plant",-3.2,0.9],
          ["plant",3.2,0.9],
          ["sofa",0,0.9]
        ]
      },
      {
        "type": "hall",
        "cx": 3.8,
        "cz": 6.4,
        "w": 6.4,
        "len": 7.6,
        "name": "Drafting bay",
        "paint": "white",
        "floorCol": "oak",
        "doors": [
          [2,0.737,"int_hard",1,2.05]
        ],
        "wins": [
          [3,0.5,"pano"],
          [0,0.5,"pano"]
        ],
        "furniture": [
          ["desk",-2.3,-1.4],
          ["chair",-2.3,-0.62,2],
          ["desk",0,-1.4],
          ["chair",0,-0.62,2],
          ["desk",2.3,-1.4],
          ["chair",2.3,-0.62,2],
          ["desk",-2.3,1.4],
          ["chair",-2.3,2.18,2],
          ["desk",0,1.4],
          ["chair",0,2.18,2],
          ["desk",2.3,1.4],
          ["chair",2.3,2.18,2],
          ["plant",3.2,-2.5]
        ]
      },
      {
        "type": "hall",
        "cx": 10.3,
        "cz": 2.3,
        "w": 4.6,
        "len": 4.6,
        "name": "Client pitch room",
        "paint": "greige",
        "floorCol": "walnut",
        "doors": [
          [3,0.348,"int_panel",0.9,2.05]
        ],
        "wins": [
          [1,0.5,"pano"],
          [2,0.5,"pano"]
        ],
        "furniture": [
          ["table",-1,0],
          ["chair",-1,-0.95],
          ["chair",-1,0.95,2],
          ["table",0,0],
          ["chair",0,-0.95],
          ["chair",0,0.95,2],
          ["table",1,0],
          ["chair",1,-0.95],
          ["chair",1,0.95,2],
          ["tv",-1.4,1.9]
        ]
      },
      {
        "type": "bedroom",
        "cx": 9.3,
        "cz": 6.4,
        "w": 3.6,
        "len": 3.4,
        "name": "Material library",
        "paint": "sage",
        "floorCol": "walnut",
        "doors": [
          [3,0.5,"int_hard",0.85,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      },
      {
        "type": "bath",
        "cx": 8.5,
        "cz": 9.4,
        "w": 2.4,
        "len": 1.8,
        "name": "Washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [3,0.292,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [0,0.5]
        ]
      }
    ]
  },
  "off_clinic": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hall",
        "cx": 3.2,
        "cz": 2.3,
        "w": 4.6,
        "len": 6.4,
        "name": "Waiting room",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.281,"ext_glass",1.8,2.3],
          [0,0.25,"int_hard",0.85,2.05]
        ],
        "wins": [
          [2,0.781,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["chair",-1.275,-1.15,2],
          ["chair",-0.425,-1.15,2],
          ["chair",0.425,-1.15,2],
          ["chair",1.275,-1.15,2],
          ["chair",-1.275,0.35,2],
          ["chair",-0.425,0.35,2],
          ["chair",0.425,0.35,2],
          ["chair",1.275,0.35,2],
          ["plant",2.6,1.5],
          ["coffee",-1.6,1.5]
        ]
      },
      {
        "type": "hall",
        "cx": 7.9,
        "cz": 2.3,
        "w": 4.6,
        "len": 3,
        "name": "Reception & records",
        "paint": "white",
        "floorCol": "wtile",
        "doors": [
          [3,0.783,"int_hard",0.85,2.05]
        ],
        "wins": [
          [2,0.5]
        ],
        "furniture": [
          ["desk",-0.7,-1.2],
          ["chair",-0.7,-0.3,2],
          ["wardrobe",1,0.8,1]
        ]
      },
      {
        "type": "hallway",
        "cx": 3.25,
        "cz": 5.3,
        "w": 1.4,
        "len": 6.5,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "wtile",
        "doors": [
          [1,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "hallway",
        "cx": 8.95,
        "cz": 5.3,
        "w": 1.4,
        "len": 4.9,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "wtile",
        "doors": [
          [3,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "bedroom",
        "cx": 1.8,
        "cz": 7.8,
        "w": 3.6,
        "len": 3.6,
        "name": "Consultation 1",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.5,"int_mdf",0.85,2.05]
        ],
        "wins": [
          [0,0.5],
          [3,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 5.4,
        "cz": 7.8,
        "w": 3.6,
        "len": 3.6,
        "name": "Consultation 2",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.5,"int_mdf",0.85,2.05]
        ],
        "wins": [
          [0,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 9,
        "cz": 7.8,
        "w": 3.6,
        "len": 3.6,
        "name": "Consultation 3",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.5,"int_mdf",0.85,2.05]
        ],
        "wins": [
          [0,0.5],
          [1,0.5]
        ]
      },
      {
        "type": "bath",
        "cx": 10.4,
        "cz": 3.4,
        "w": 2.4,
        "len": 2,
        "name": "Washroom",
        "paint": "white",
        "floorCol": "wtile",
        "doors": [
          [0,0.5,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [2,0.5]
        ]
      }
    ]
  },
  "off_law": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hall",
        "cx": 2.8,
        "cz": 2.5,
        "w": 5,
        "len": 5.6,
        "name": "Reception",
        "paint": "beige",
        "floorCol": "walnut",
        "doors": [
          [2,0.232,"ext_glass",1.8,2.3],
          [0,0.821,"int_hard",0.85,2.05]
        ],
        "wins": [
          [2,0.732,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["desk",-1.5,-1.1],
          ["chair",-1.5,-0.2,2],
          ["sofa",1.3,-1.3],
          ["coffee",1.3,-0.2],
          ["plant",2.2,1.6]
        ]
      },
      {
        "type": "hall",
        "cx": 8.8,
        "cz": 2.5,
        "w": 5,
        "len": 6.4,
        "name": "Conference room",
        "paint": "greige",
        "floorCol": "walnut",
        "doors": [
          [0,0.469,"int_panel",0.9,2.1]
        ],
        "wins": [
          [2,0.5,"pano"]
        ],
        "furniture": [
          ["table",-2.2,0],
          ["chair",-2.2,-0.95],
          ["chair",-2.2,0.95,2],
          ["table",-1.1,0],
          ["chair",-1.1,-0.95],
          ["chair",-1.1,0.95,2],
          ["table",0,0],
          ["chair",0,-0.95],
          ["chair",0,0.95,2],
          ["table",1.1,0],
          ["chair",1.1,-0.95],
          ["chair",1.1,0.95,2],
          ["table",2.2,0],
          ["chair",2.2,-0.95],
          ["chair",2.2,0.95,2],
          ["plant",-2.6,1.4]
        ]
      },
      {
        "type": "hall",
        "cx": 13.7,
        "cz": 2.5,
        "w": 5,
        "len": 3.4,
        "name": "Law library",
        "paint": "sage",
        "floorCol": "walnut",
        "doors": [
          [0,0.5,"int_hard",0.85,2.05]
        ],
        "wins": [
          [1,0.5]
        ],
        "furniture": [
          ["wardrobe",-1.2,-0.8,1],
          ["wardrobe",-1.2,0.8,1],
          ["table",0.5,0],
          ["chair",0.5,-0.9],
          ["chair",0.5,0.9,2]
        ]
      },
      {
        "type": "hallway",
        "cx": 3.85,
        "cz": 5.7,
        "w": 1.4,
        "len": 7.7,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "ash",
        "doors": [
          [1,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "hallway",
        "cx": 11.55,
        "cz": 5.7,
        "w": 1.4,
        "len": 7.7,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "ash",
        "doors": [
          [3,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "bedroom",
        "cx": 1.7,
        "cz": 8.4,
        "w": 4,
        "len": 3.4,
        "name": "Partner cabin",
        "paint": "beige",
        "floorCol": "walnut",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5],
          [3,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 5.1,
        "cz": 8.4,
        "w": 4,
        "len": 3.4,
        "name": "Partner cabin",
        "paint": "beige",
        "floorCol": "walnut",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 8.5,
        "cz": 8.4,
        "w": 4,
        "len": 3.4,
        "name": "Partner cabin",
        "paint": "beige",
        "floorCol": "walnut",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 11.9,
        "cz": 8.4,
        "w": 4,
        "len": 3.4,
        "name": "Partner cabin",
        "paint": "beige",
        "floorCol": "walnut",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5]
        ]
      },
      {
        "type": "bath",
        "cx": 14.5,
        "cz": 7.6,
        "w": 2.4,
        "len": 1.8,
        "name": "Washroom",
        "paint": "white",
        "floorCol": "wtile",
        "doors": [
          [2,0.5,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      }
    ]
  },
  "off_finance": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hall",
        "cx": 3,
        "cz": 2.4,
        "w": 4.8,
        "len": 6,
        "name": "Client lounge",
        "paint": "cream",
        "floorCol": "oak",
        "doors": [
          [2,0.267,"ext_glass",1.8,2.3],
          [0,0.817,"int_hard",0.85,2.05]
        ],
        "wins": [
          [2,0.767,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["sofa",-1.5,-1.3],
          ["coffee",-1.5,-0.2],
          ["desk",1.6,-1.1],
          ["chair",1.6,-0.2,2],
          ["plant",2.3,1.6]
        ]
      },
      {
        "type": "bedroom",
        "cx": 7.8,
        "cz": 2.4,
        "w": 4.8,
        "len": 3.6,
        "name": "Partner cabin",
        "paint": "beige",
        "floorCol": "walnut",
        "doors": [
          [0,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [2,0.5,"pano"]
        ]
      },
      {
        "type": "hallway",
        "cx": 3.1,
        "cz": 5.5,
        "w": 1.4,
        "len": 6.2,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [1,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "hallway",
        "cx": 8.9,
        "cz": 5.5,
        "w": 1.4,
        "len": 5.4,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [3,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "hall",
        "cx": 3.7,
        "cz": 8.8,
        "w": 5.2,
        "len": 7.4,
        "name": "Accounts work bay",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [2,0.595,"int_hard",0.9,2.05]
        ],
        "wins": [
          [0,0.5,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["desk",-2.2,-1.15],
          ["chair",-2.2,-0.37,2],
          ["desk",0,-1.15],
          ["chair",0,-0.37,2],
          ["desk",2.2,-1.15],
          ["chair",2.2,-0.37,2],
          ["desk",-2.2,1.15],
          ["chair",-2.2,1.93,2],
          ["desk",0,1.15],
          ["chair",0,1.93,2],
          ["desk",2.2,1.15],
          ["chair",2.2,1.93,2],
          ["plant",3,-2]
        ]
      },
      {
        "type": "bedroom",
        "cx": 8.6,
        "cz": 7.8,
        "w": 3.2,
        "len": 2.4,
        "name": "Archive",
        "paint": "gray",
        "floorCol": "slate",
        "doors": [
          [2,0.5,"int_hard",0.85,2.05]
        ],
        "furniture": [
          ["wardrobe",-0.7,-0.5,1],
          ["wardrobe",-0.7,0.5,1],
          ["wardrobe",0.7,-0.5,1]
        ]
      },
      {
        "type": "bath",
        "cx": 10.7,
        "cz": 7.4,
        "w": 2.4,
        "len": 1.8,
        "name": "Washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.5,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      },
      {
        "type": "kitchen",
        "cx": 10.6,
        "cz": 3.6,
        "w": 2.4,
        "len": 2,
        "name": "Pantry",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [0,0.5,"int_hard",0.85,2.05]
        ],
        "wins": [
          [2,0.5]
        ]
      }
    ]
  },
  "off_retail": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hall",
        "cx": 3.9,
        "cz": 3.8,
        "w": 7.6,
        "len": 7.8,
        "name": "Showroom",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [2,0.5,"ext_glass",2.4,2.4]
        ],
        "wins": [
          [2,0.846,"pano"],
          [2,0.154,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["wardrobe",-2.8,-3],
          ["wardrobe",-0.9,-3],
          ["wardrobe",1,-3],
          ["table",-2,0.4],
          ["table",1.2,0.4],
          ["sofa",-2,2.6],
          ["plant",3.2,2.8],
          ["plant",3.2,-3]
        ]
      },
      {
        "type": "hall",
        "cx": 9.6,
        "cz": 1.2,
        "w": 2.4,
        "len": 3.6,
        "name": "Sales counter",
        "paint": "greige",
        "floorCol": "gtile",
        "doors": [
          [3,0.5,"int_hard",1,2.05]
        ],
        "wins": [
          [1,0.5,"pano"]
        ],
        "furniture": [
          ["desk",-0.9,-0.5],
          ["chair",-0.9,0.3,2],
          ["desk",0.7,-0.5]
        ]
      },
      {
        "type": "hallway",
        "cx": 8.6,
        "cz": 5.6,
        "rot": 1,
        "w": 1.6,
        "len": 6.4,
        "name": "Service corridor",
        "paint": "white",
        "floorCol": "slate",
        "doors": [
          [2,0.719,"int_hard",0.9,2.05]
        ]
      },
      {
        "type": "bedroom",
        "cx": 11,
        "cz": 3.9,
        "w": 3,
        "len": 3.2,
        "name": "Back office",
        "paint": "gray",
        "floorCol": "ash",
        "doors": [
          [3,0.5,"int_hard",0.85,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 11,
        "cz": 7.1,
        "w": 3.4,
        "len": 3.2,
        "name": "Inventory",
        "paint": "gray",
        "floorCol": "slate",
        "doors": [
          [3,0.5,"int_hard",0.9,2.05]
        ],
        "wins": [
          [1,0.5]
        ],
        "furniture": [
          ["wardrobe",-1.1,-0.6,1],
          ["wardrobe",1.1,-0.6,1],
          ["wardrobe",-1.1,0.6,1],
          ["wardrobe",1.1,0.6,1]
        ]
      },
      {
        "type": "bath",
        "cx": 8.7,
        "cz": 10,
        "w": 2.4,
        "len": 1.8,
        "name": "Staff washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.556,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [0,0.5]
        ]
      }
    ]
  },
  "off_bpo": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hallway",
        "cx": 8,
        "cz": 1.3,
        "rot": 1,
        "w": 2.4,
        "len": 2.6,
        "name": "Lobby",
        "paint": "white",
        "floorCol": "slate",
        "doors": [
          [1,0.5,"ext_glass",1.8,2.3]
        ]
      },
      {
        "type": "hall",
        "cx": 3.4,
        "cz": 3.7,
        "w": 7.4,
        "len": 6.8,
        "name": "Agent bay A",
        "paint": "gray",
        "floorCol": "gtile",
        "doors": [
          [1,0.824,"int_hard",0.9,2.05]
        ],
        "wins": [
          [3,0.5,"pano"],
          [2,0.5,"pano"]
        ],
        "furniture": [
          ["desk",-2,-2.2],
          ["chair",-2,-1.42,2],
          ["desk",0,-2.2],
          ["chair",0,-1.42,2],
          ["desk",2,-2.2],
          ["chair",2,-1.42,2],
          ["desk",-2,0],
          ["chair",-2,0.78,2],
          ["desk",0,0],
          ["chair",0,0.78,2],
          ["desk",2,0],
          ["chair",2,0.78,2],
          ["desk",-2,2.2],
          ["chair",-2,2.98,2],
          ["desk",0,2.2],
          ["chair",0,2.98,2],
          ["desk",2,2.2],
          ["chair",2,2.98,2]
        ]
      },
      {
        "type": "hall",
        "cx": 12.6,
        "cz": 3.7,
        "w": 7.4,
        "len": 6.8,
        "name": "Agent bay B",
        "paint": "gray",
        "floorCol": "gtile",
        "doors": [
          [3,0.176,"int_hard",0.9,2.05]
        ],
        "wins": [
          [1,0.5,"pano"],
          [2,0.5,"pano"]
        ],
        "furniture": [
          ["desk",-2,-2.2],
          ["chair",-2,-1.42,2],
          ["desk",0,-2.2],
          ["chair",0,-1.42,2],
          ["desk",2,-2.2],
          ["chair",2,-1.42,2],
          ["desk",-2,0],
          ["chair",-2,0.78,2],
          ["desk",0,0],
          ["chair",0,0.78,2],
          ["desk",2,0],
          ["chair",2,0.78,2],
          ["desk",-2,2.2],
          ["chair",-2,2.98,2],
          ["desk",0,2.2],
          ["chair",0,2.98,2],
          ["desk",2,2.2],
          ["chair",2,2.98,2]
        ]
      },
      {
        "type": "hallway",
        "cx": 8,
        "cz": 5,
        "rot": 1,
        "w": 2.4,
        "len": 4.8,
        "name": "Spine",
        "paint": "white",
        "floorCol": "slate",
        "doors": [
          [1,0.5,"int_hard",1,2.05]
        ]
      },
      {
        "type": "bedroom",
        "cx": 1.8,
        "cz": 9.2,
        "w": 3.6,
        "len": 3.6,
        "name": "Manager cabin",
        "paint": "beige",
        "floorCol": "ash",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5],
          [3,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 5.4,
        "cz": 9.2,
        "w": 3.6,
        "len": 3.6,
        "name": "Training room",
        "paint": "sage",
        "floorCol": "ash",
        "doors": [
          [2,0.5,"int_hard",0.85,2.05]
        ],
        "wins": [
          [0,0.5]
        ]
      },
      {
        "type": "kitchen",
        "cx": 9.6,
        "cz": 9.4,
        "w": 4,
        "len": 4.8,
        "name": "Cafeteria",
        "paint": "terra",
        "floorCol": "terra",
        "doors": [
          [2,0.417,"int_hard",0.9,2.05]
        ],
        "wins": [
          [0,0.5,"pano"]
        ],
        "furniture": [
          ["kunit",-1.3,-1.5],
          ["fridge",1.9,-1.5],
          ["table",-1.05,0.8],
          ["chair",-2,0.8,1],
          ["chair",-0.1,0.8,3],
          ["table",1.05,0.8],
          ["chair",0.1,0.8,1],
          ["chair",2,0.8,3]
        ]
      },
      {
        "type": "bath",
        "cx": 13.1,
        "cz": 8.6,
        "w": 2.4,
        "len": 2.2,
        "name": "Washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.5,"int_pvc",0.8,2.05]
        ]
      },
      {
        "type": "bath",
        "cx": 15.1,
        "cz": 8.6,
        "w": 2.4,
        "len": 1.8,
        "name": "Washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.5,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      }
    ]
  },
  "off_realestate": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hall",
        "cx": 2.5,
        "cz": 2.3,
        "w": 4.6,
        "len": 5,
        "name": "Model foyer",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [2,0.28,"ext_glass",2,2.4],
          [0,0.5,"int_hard",0.85,2.05],
          [1,0.565,"int_hard",1,2.05]
        ],
        "wins": [
          [2,0.76,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["table",-0.9,0],
          ["desk",1.4,-1.2],
          ["chair",1.4,-0.4,2],
          ["plant",1.9,1.5]
        ]
      },
      {
        "type": "hall",
        "cx": 8.5,
        "cz": 2.3,
        "w": 4.6,
        "len": 7,
        "name": "Presentation lounge",
        "paint": "greige",
        "floorCol": "walnut",
        "doors": [
          [0,0.429,"int_hard",0.85,2.05]
        ],
        "wins": [
          [2,0.5,"pano"],
          [1,0.5,"pano"]
        ],
        "furniture": [
          ["sofa",-2.2,-1.3],
          ["sofa",0.2,-1.3],
          ["coffee",-1,-0.2],
          ["tv",-1,1.5],
          ["table",1.5,0.2],
          ["chair",1.5,-0.75],
          ["chair",1.5,1.15,2],
          ["table",2.5,0.2],
          ["chair",2.5,-0.75],
          ["chair",2.5,1.15,2]
        ]
      },
      {
        "type": "hallway",
        "cx": 3.1,
        "cz": 5.3,
        "w": 1.4,
        "len": 6.2,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "ash",
        "doors": [
          [1,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "hallway",
        "cx": 9.1,
        "cz": 5.3,
        "w": 1.4,
        "len": 5.8,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "ash",
        "doors": [
          [3,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "bedroom",
        "cx": 1.6,
        "cz": 7.8,
        "w": 3.6,
        "len": 3.2,
        "name": "Closing room",
        "paint": "cream",
        "floorCol": "oak",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5],
          [3,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 4.8,
        "cz": 7.8,
        "w": 3.6,
        "len": 3.2,
        "name": "Closing room",
        "paint": "cream",
        "floorCol": "oak",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 8,
        "cz": 7.8,
        "w": 3.6,
        "len": 3.2,
        "name": "Closing room",
        "paint": "cream",
        "floorCol": "oak",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5]
        ]
      },
      {
        "type": "kitchen",
        "cx": 10.8,
        "cz": 7.1,
        "w": 2.2,
        "len": 2.4,
        "name": "Pantry",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.5,"int_hard",0.85,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      }
    ]
  },
  "off_satellite": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hall",
        "cx": 2.7,
        "cz": 2.1,
        "w": 4.2,
        "len": 5.4,
        "name": "Coffee lounge",
        "paint": "cream",
        "floorCol": "oak",
        "doors": [
          [2,0.222,"ext_glass",1.8,2.3],
          [1,0.524,"int_hard",0.9,2.05]
        ],
        "wins": [
          [2,0.741,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["sofa",-1.2,-1.1],
          ["coffee",-1.2,-0.1],
          ["kunit",1.4,-1.2],
          ["table",1,1],
          ["chair",1,0.3],
          ["plant",2.1,1.3]
        ]
      },
      {
        "type": "hallway",
        "cx": 6.1,
        "cz": 2.8,
        "rot": 1,
        "w": 1.4,
        "len": 5.6,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "ash",
        "doors": [
          [3,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "hallway",
        "cx": 6.1,
        "cz": 8.3,
        "rot": 1,
        "w": 1.4,
        "len": 5.4,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "ash",
        "doors": [
          [1,0.5,"int_hard",0.85,2.05]
        ]
      },
      {
        "type": "bedroom",
        "cx": 8.5,
        "cz": 1.6,
        "w": 3.2,
        "len": 3.4,
        "name": "Private office",
        "paint": "beige",
        "floorCol": "ash",
        "doors": [
          [3,0.5,"int_mdf",0.85,2.05]
        ],
        "wins": [
          [1,0.5],
          [2,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 8.5,
        "cz": 4.8,
        "w": 3.2,
        "len": 3.4,
        "name": "Private office",
        "paint": "beige",
        "floorCol": "ash",
        "doors": [
          [3,0.437,"int_mdf",0.85,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 3.7,
        "cz": 5.9,
        "w": 3.4,
        "len": 3.4,
        "name": "Private office",
        "paint": "beige",
        "floorCol": "ash",
        "doors": [
          [1,0.412,"int_mdf",0.85,2.05]
        ],
        "wins": [
          [3,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 3.7,
        "cz": 9.3,
        "w": 3.4,
        "len": 3.4,
        "name": "Private office",
        "paint": "beige",
        "floorCol": "ash",
        "doors": [
          [1,0.5,"int_mdf",0.85,2.05]
        ],
        "wins": [
          [3,0.5],
          [0,0.5]
        ]
      },
      {
        "type": "hall",
        "cx": 8.8,
        "cz": 8.4,
        "w": 4,
        "len": 4,
        "name": "Shared meeting room",
        "paint": "greige",
        "floorCol": "walnut",
        "doors": [
          [3,0.175,"int_panel",0.9,2.05]
        ],
        "wins": [
          [1,0.5,"pano"],
          [0,0.5,"pano"]
        ],
        "furniture": [
          ["table",-1,0],
          ["chair",-1,-0.95],
          ["chair",-1,0.95,2],
          ["table",0,0],
          ["chair",0,-0.95],
          ["chair",0,0.95,2],
          ["table",1,0],
          ["chair",1,-0.95],
          ["chair",1,0.95,2],
          ["tv",-1.1,1.5]
        ]
      },
      {
        "type": "bath",
        "cx": 6.4,
        "cz": 12.2,
        "w": 2.4,
        "len": 2,
        "name": "Washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.65,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [0,0.5]
        ]
      }
    ]
  },
  "oth_japandi": {
    "v": 2,
    "profile": "home",
    "rooms": [
      {
        "type": "veranda",
        "cx": 3,
        "cz": 1.3,
        "w": 2.6,
        "len": 6,
        "name": "Engawa veranda",
        "floorCol": "oak"
      },
      {
        "type": "hall",
        "cx": 3.7,
        "cz": 5.3,
        "w": 5.4,
        "len": 7.4,
        "name": "Living",
        "paint": "cream",
        "floorCol": "oak",
        "doors": [
          [2,0.595,"ext_glass",2.2,2.3]
        ],
        "wins": [
          [3,0.259,"pano"],
          [3,0.741,"pano"],
          [1,0.185]
        ],
        "furniture": [
          ["sofa",-1.9,-1.2],
          ["coffee",-1.9,-0.1],
          ["tv",-1.9,1.4],
          ["table",1.9,0.4],
          ["chair",1.2,0.4,1],
          ["chair",2.6,0.4,3],
          ["plant",3.2,-1.9]
        ]
      },
      {
        "type": "kitchen",
        "cx": 8.9,
        "cz": 4.3,
        "w": 3.4,
        "len": 3,
        "name": "Kitchen",
        "paint": "greige",
        "floorCol": "honey",
        "doors": [
          [3,0.412,"int_hard",0.9,2.05]
        ],
        "wins": [
          [1,0.5],
          [2,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 2.3,
        "cz": 10,
        "w": 4,
        "len": 4.6,
        "name": "Master bedroom",
        "paint": "beige",
        "floorCol": "oak",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5,"pano"],
          [3,0.5]
        ]
      },
      {
        "type": "bath",
        "cx": 5.8,
        "cz": 9.3,
        "w": 2.6,
        "len": 2.4,
        "name": "Master bath",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [3,0.5,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [1,0.5]
        ],
        "furniture": [
          ["bath",-0.2,0.6],
          ["toilet",-0.7,-0.6],
          ["basin",0.6,-0.6]
        ]
      }
    ]
  },
  "oth_cabin": {
    "v": 2,
    "profile": "home",
    "rooms": [
      {
        "type": "veranda",
        "cx": 2.7,
        "cz": 1.2,
        "w": 2.4,
        "len": 5.4,
        "name": "Deck",
        "floorCol": "walnut"
      },
      {
        "type": "hall",
        "cx": 3.3,
        "cz": 5.4,
        "w": 6,
        "len": 6.6,
        "name": "Great room",
        "paint": "white",
        "floorCol": "walnut",
        "doors": [
          [2,0.591,"ext_hard",1,2.1]
        ],
        "wins": [
          [3,0.5,"pano"],
          [0,0.5,"pano"]
        ],
        "furniture": [
          ["sofa",-1.6,-1.6],
          ["coffee",-1.6,-0.5],
          ["tv",-1.6,1.4],
          ["table",1.7,-0.6],
          ["chair",1,-0.6,1],
          ["chair",2.4,-0.6,3],
          ["plant",2.5,2.2]
        ]
      },
      {
        "type": "kitchen",
        "cx": 7.9,
        "cz": 3.8,
        "w": 2.8,
        "len": 2.6,
        "name": "Kitchenette",
        "paint": "greige",
        "floorCol": "honey",
        "doors": [
          [3,0.5,"int_hard",0.9,2.05]
        ],
        "wins": [
          [1,0.5],
          [2,0.5]
        ]
      },
      {
        "type": "bath",
        "cx": 7.6,
        "cz": 6.3,
        "w": 2.2,
        "len": 2,
        "name": "Compact bath",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [3,0.5,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      }
    ]
  },
  "oth_loft": {
    "v": 2,
    "profile": "home",
    "rooms": [
      {
        "type": "hall",
        "cx": 3.9,
        "cz": 3.2,
        "w": 6.4,
        "len": 7.8,
        "name": "Living",
        "paint": "gray",
        "floorCol": "slate",
        "doors": [
          [2,0.5,"ext_glass",2.4,2.4]
        ],
        "wins": [
          [2,0.821,"pano"],
          [3,0.5,"pano"],
          [2,0.179,"pano"]
        ],
        "furniture": [
          ["sofa",-2.2,-1.9],
          ["sofa",0.4,-1.9],
          ["coffee",-0.9,-0.7],
          ["tv",-0.9,1.6],
          ["table",2.4,1.6],
          ["chair",1.7,1.6,1],
          ["chair",3.1,1.6,3],
          ["plant",3.2,-2.4]
        ]
      },
      {
        "type": "kitchen",
        "cx": 9.6,
        "cz": 1.8,
        "w": 3.6,
        "len": 3.6,
        "name": "Kitchen",
        "paint": "white",
        "floorCol": "slate",
        "doors": [
          [3,0.5,"int_hard",0.9,2.05]
        ],
        "wins": [
          [1,0.5,"pano"],
          [2,0.5]
        ]
      },
      {
        "type": "balcony",
        "cx": 9.6,
        "cz": 4.8,
        "w": 2.4,
        "len": 3.6,
        "name": "Terrace",
        "floorCol": "slate"
      },
      {
        "type": "bedroom",
        "cx": 2.4,
        "cz": 8.4,
        "w": 4,
        "len": 4.8,
        "name": "Bedroom",
        "paint": "greige",
        "floorCol": "walnut",
        "doors": [
          [2,0.5,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5,"pano"],
          [3,0.5]
        ]
      },
      {
        "type": "bath",
        "cx": 6.3,
        "cz": 8.1,
        "w": 3.4,
        "len": 3,
        "name": "Luxury bath",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [3,0.5,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [1,0.5],
          [0,0.5]
        ],
        "furniture": [
          ["bath",0.4,0.9],
          ["shower",-0.9,0.9],
          ["toilet",-0.9,-0.9],
          ["basin",0.6,-1]
        ]
      }
    ]
  },
  "oth_wellness": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hall",
        "cx": 2.8,
        "cz": 2.2,
        "w": 4.4,
        "len": 5.6,
        "name": "Reception lounge",
        "paint": "sage",
        "floorCol": "oak",
        "doors": [
          [2,0.232,"ext_glass",1.8,2.3],
          [0,0.357,"int_hard",0.9,2.05],
          [1,0.659,"int_hard",0.9,2.05],
          [1,0.159,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [2,0.75,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["sofa",-1.4,-1.2],
          ["coffee",-1.4,-0.2],
          ["desk",1.4,-1.2],
          ["chair",1.4,-0.3,2],
          ["plant",2.2,1.4]
        ]
      },
      {
        "type": "hall",
        "cx": 4,
        "cz": 7.9,
        "w": 7,
        "len": 8,
        "name": "Practice hall",
        "paint": "white",
        "floorCol": "oak",
        "doors": [
          [2,0.75,"int_hard",0.9,2.05],
          [1,0.771,"int_hard",0.9,2.05]
        ],
        "wins": [
          [0,0.5,"pano"],
          [3,0.5,"pano"],
          [0,0.825,"pano"]
        ],
        "furniture": [
          ["plant",-3.4,-3],
          ["plant",3.4,-3],
          ["plant",-3.4,3],
          ["walllamp",0,3.2]
        ]
      },
      {
        "type": "bedroom",
        "cx": 7.1,
        "cz": 1.5,
        "w": 3,
        "len": 3,
        "name": "Changing room",
        "paint": "lavender",
        "floorCol": "wtile",
        "doors": [
          [3,0.5,"int_hard",0.9,2.05]
        ],
        "wins": [
          [1,0.5],
          [2,0.5]
        ],
        "furniture": [
          ["wardrobe",-0.9,-0.4,1],
          ["wardrobe",0.9,-0.4,1],
          ["chair",0,0.7]
        ]
      },
      {
        "type": "bath",
        "cx": 6.7,
        "cz": 3.7,
        "w": 1.4,
        "len": 2.2,
        "name": "Washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [3,0.5,"int_pvc",0.8,2.05]
        ],
        "furniture": [
          ["toilet",-0.6,-0.2],
          ["basin",0.6,-0.3]
        ]
      },
      {
        "type": "bedroom",
        "cx": 9.6,
        "cz": 6,
        "w": 3.2,
        "len": 3.2,
        "name": "Treatment room",
        "paint": "mint",
        "floorCol": "oak",
        "doors": [
          [3,0.5,"int_mdf",0.85,2.05]
        ],
        "wins": [
          [1,0.5],
          [2,0.5]
        ]
      }
    ]
  },
  "oth_training": {
    "v": 2,
    "profile": "office",
    "rooms": [
      {
        "type": "hall",
        "cx": 2.5,
        "cz": 1.8,
        "w": 3.6,
        "len": 5,
        "name": "Entrance foyer",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [2,0.68,"ext_glass",2,2.4],
          [0,0.5,"int_hard",0.9,2.05],
          [1,0.5,"int_hard",1,2.05]
        ],
        "wins": [
          [2,0.24,"pano"]
        ],
        "furniture": [
          ["desk",-1.2,-0.8],
          ["chair",-1.2,0,2],
          ["plant",1.9,1.1],
          ["sofa",0.6,-1.1]
        ]
      },
      {
        "type": "hall",
        "cx": 8.9,
        "cz": 3.5,
        "w": 7,
        "len": 7.8,
        "name": "Lecture hall",
        "paint": "greige",
        "floorCol": "gtile",
        "doors": [
          [3,0.257,"int_hard",1,2.05]
        ],
        "wins": [
          [2,0.513,"pano"],
          [1,0.5,"pano"],
          [0,0.705,"pano"]
        ],
        "furniture": [
          ["chair",-2,-0.9,2],
          ["chair",-1.2,-0.9,2],
          ["chair",-0.4,-0.9,2],
          ["chair",0.4,-0.9,2],
          ["chair",1.2,-0.9,2],
          ["chair",2,-0.9,2],
          ["chair",-2,0.1,2],
          ["chair",-1.2,0.1,2],
          ["chair",-0.4,0.1,2],
          ["chair",0.4,0.1,2],
          ["chair",1.2,0.1,2],
          ["chair",2,0.1,2],
          ["chair",-2,1.1,2],
          ["chair",-1.2,1.1,2],
          ["chair",-0.4,1.1,2],
          ["chair",0.4,1.1,2],
          ["chair",1.2,1.1,2],
          ["chair",2,1.1,2],
          ["chair",-2,2.1,2],
          ["chair",-1.2,2.1,2],
          ["chair",-0.4,2.1,2],
          ["chair",0.4,2.1,2],
          ["chair",1.2,2.1,2],
          ["chair",2,2.1,2],
          ["desk",0,-2.6],
          ["tv",-2.4,-2.9]
        ]
      },
      {
        "type": "hallway",
        "cx": 2.5,
        "cz": 4.3,
        "w": 1.4,
        "len": 5,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [2,0.5,"int_hard",0.9,2.05],
          [1,0.5,"int_hard",0.9,2.05]
        ]
      },
      {
        "type": "hallway",
        "cx": 4.3,
        "cz": 7.5,
        "rot": 1,
        "w": 1.4,
        "len": 5,
        "name": "Corridor",
        "paint": "white",
        "floorCol": "gtile",
        "doors": [
          [1,0.5,"int_hard",0.9,2.05]
        ]
      },
      {
        "type": "bedroom",
        "cx": 1.8,
        "cz": 6.7,
        "w": 3.4,
        "len": 3.6,
        "name": "Seminar room",
        "paint": "sage",
        "floorCol": "ash",
        "doors": [
          [1,0.5,"int_mdf",0.85,2.05]
        ],
        "wins": [
          [3,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 1.8,
        "cz": 10.1,
        "w": 3.4,
        "len": 3.6,
        "name": "Seminar room",
        "paint": "sage",
        "floorCol": "ash",
        "doors": [
          [1,0.676,"int_mdf",0.85,2.05]
        ],
        "wins": [
          [3,0.5],
          [0,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 6.7,
        "cz": 8.4,
        "w": 2.8,
        "len": 3.4,
        "name": "Administration",
        "paint": "beige",
        "floorCol": "ash",
        "doors": [
          [3,0.5,"int_mdf",0.85,2.05]
        ],
        "wins": [
          [1,0.5],
          [0,0.5]
        ]
      },
      {
        "type": "bath",
        "cx": 4.4,
        "cz": 11.2,
        "w": 2.4,
        "len": 1.6,
        "name": "Washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.625,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      }
    ]
  },
  "oth_cafe": {
    "v": 2,
    "profile": "home",
    "rooms": [
      {
        "type": "hall",
        "cx": 3.8,
        "cz": 2.8,
        "w": 5.6,
        "len": 7.6,
        "name": "Dining lounge",
        "paint": "cream",
        "floorCol": "honey",
        "doors": [
          [2,0.526,"ext_glass",2,2.3],
          [1,0.286,"int_hard",1,2.05],
          [0,0.289,"int_hard",0.9,2.05],
          [0,0.908,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [2,0.842,"pano"],
          [2,0.184,"pano"],
          [3,0.5,"pano"]
        ],
        "furniture": [
          ["table",-2.2,-1.3],
          ["chair",-3.15,-1.3,1],
          ["chair",-1.25,-1.3,3],
          ["table",0,-1.3],
          ["chair",-0.95,-1.3,1],
          ["chair",0.95,-1.3,3],
          ["table",2.2,-1.3],
          ["chair",1.25,-1.3,1],
          ["chair",3.15,-1.3,3],
          ["table",-2.2,1.3],
          ["chair",-3.15,1.3,1],
          ["chair",-1.25,1.3,3],
          ["table",0,1.3],
          ["chair",-0.95,1.3,1],
          ["chair",0.95,1.3,3],
          ["table",2.2,1.3],
          ["chair",1.25,1.3,1],
          ["chair",3.15,1.3,3]
        ]
      },
      {
        "type": "veranda",
        "cx": 9.3,
        "cz": 1.2,
        "w": 2.4,
        "len": 3.4,
        "name": "Terrace seating",
        "floorCol": "terra"
      },
      {
        "type": "hall",
        "cx": 9.3,
        "cz": 4,
        "w": 3.2,
        "len": 3.4,
        "name": "Coffee bar",
        "paint": "terra",
        "floorCol": "terra",
        "doors": [
          [3,0.5,"int_hard",1,2.05]
        ],
        "wins": [
          [1,0.5,"pano"]
        ],
        "furniture": [
          ["kunit",0,-1.1],
          ["kunit",-1.2,0,1],
          ["fridge",1.2,1],
          ["chair",-0.2,0.9],
          ["chair",0.8,0.9]
        ]
      },
      {
        "type": "kitchen",
        "cx": 2,
        "cz": 7.3,
        "w": 3.4,
        "len": 4,
        "name": "Kitchen",
        "paint": "white",
        "floorCol": "wtile",
        "doors": [
          [2,0.45,"int_hard",0.9,2.05],
          [1,0.618,"int_hard",0.9,2.05]
        ],
        "wins": [
          [0,0.5],
          [3,0.5]
        ],
        "furniture": [
          ["kunit",-0.9,-1.1],
          ["kunit",0.6,-1.1],
          ["fridge",1.5,1.1],
          ["table",-0.8,0.9]
        ]
      },
      {
        "type": "kitchen",
        "cx": 5,
        "cz": 6.9,
        "w": 2.6,
        "len": 2,
        "name": "Prep & store",
        "paint": "white",
        "floorCol": "wtile",
        "doors": [
          [3,0.5,"int_hard",0.9,2.05]
        ],
        "wins": [
          [0,0.5]
        ]
      },
      {
        "type": "bath",
        "cx": 6.9,
        "cz": 6.8,
        "w": 2.4,
        "len": 1.8,
        "name": "Guest washroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.5,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      }
    ]
  },
  "oth_tiny": {
    "v": 2,
    "profile": "home",
    "rooms": [
      {
        "type": "veranda",
        "cx": 2,
        "cz": 0.9,
        "w": 1.8,
        "len": 4,
        "name": "Front deck",
        "floorCol": "walnut"
      },
      {
        "type": "hall",
        "cx": 2.3,
        "cz": 4.4,
        "w": 5.2,
        "len": 4.6,
        "name": "Living & kitchen",
        "paint": "white",
        "floorCol": "oak",
        "doors": [
          [2,0.565,"ext_hard",0.9,2.05]
        ],
        "wins": [
          [3,0.5,"pano"],
          [0,0.5,"pano"]
        ],
        "furniture": [
          ["sofa",-1.1,-1.6],
          ["coffee",-1.1,-0.6],
          ["kunit",1.1,-1.7],
          ["fridge",1.7,-0.6],
          ["table",0.4,1.4],
          ["chair",-0.3,1.4,1],
          ["chair",1.1,1.4,3]
        ]
      },
      {
        "type": "bath",
        "cx": 5.5,
        "cz": 2.9,
        "w": 2.2,
        "len": 1.8,
        "name": "Wet bath",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [3,0.5,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      },
      {
        "type": "stairs",
        "cx": 5.3,
        "cz": 5.5,
        "rot": 1,
        "w": 1.4,
        "len": 3,
        "name": "Loft stair",
        "paint": "white",
        "floorCol": "walnut",
        "doors": [
          [2,0.5,"int_hard",0.8,2.05]
        ]
      }
    ]
  },
  "oth_townhouse": {
    "v": 2,
    "profile": "home",
    "rooms": [
      {
        "type": "hallway",
        "cx": 0.8,
        "cz": 2.3,
        "rot": 1,
        "w": 1.6,
        "len": 4.6,
        "name": "Entry hall",
        "paint": "white",
        "floorCol": "slate",
        "doors": [
          [1,0.5,"ext_hard",0.9,2.1]
        ]
      },
      {
        "type": "hall",
        "cx": 4.2,
        "cz": 2.5,
        "w": 5,
        "len": 5.2,
        "name": "Living",
        "paint": "cream",
        "floorCol": "oak",
        "doors": [
          [3,0.32,"int_hard",0.9,2.05],
          [0,0.269,"int_hard",0.9,2.05],
          [0,0.846,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [2,0.5,"pano"],
          [1,0.5,"pano"]
        ],
        "furniture": [
          ["sofa",-1.3,-1.4],
          ["coffee",-1.3,-0.3],
          ["tv",-1.3,1.5],
          ["table",1.5,0.2],
          ["chair",0.8,0.2,1],
          ["chair",2.2,0.2,3]
        ]
      },
      {
        "type": "kitchen",
        "cx": 3.4,
        "cz": 6.3,
        "w": 2.6,
        "len": 3.6,
        "name": "Kitchen",
        "paint": "white",
        "floorCol": "wtile",
        "doors": [
          [2,0.611,"int_hard",0.9,2.05]
        ],
        "wins": [
          [0,0.778]
        ]
      },
      {
        "type": "stairs",
        "cx": 0.8,
        "cz": 6.1,
        "rot": 1,
        "w": 1.6,
        "len": 3,
        "name": "Stairs",
        "paint": "white",
        "floorCol": "slate",
        "doors": [
          [1,0.5,"int_hard",0.8,2.05]
        ]
      },
      {
        "type": "bath",
        "cx": 6.1,
        "cz": 6.2,
        "w": 2.4,
        "len": 1.8,
        "name": "Bathroom",
        "paint": "mint",
        "floorCol": "wtile",
        "doors": [
          [2,0.556,"int_pvc",0.8,2.05]
        ],
        "wins": [
          [1,0.5]
        ]
      },
      {
        "type": "bedroom",
        "cx": 1.8,
        "cz": 9.4,
        "w": 3.6,
        "len": 3.6,
        "name": "Bedroom",
        "paint": "greige",
        "floorCol": "oak",
        "doors": [
          [2,0.778,"int_panel",0.85,2.05]
        ],
        "wins": [
          [0,0.5,"pano"],
          [3,0.5]
        ]
      }
    ]
  }
};

export function getTemplateGeometry(key: string): TemplateGeometry | null {
  return Object.hasOwn(PAID_TEMPLATE_GEOMETRY, key)
    ? PAID_TEMPLATE_GEOMETRY[key]
    : null;
}
